name: Website
on:
  push:
    branches:
      - 'main'

jobs:
  # ref: https://github.com/primer/react/blob/f97a69aa124d28cf93734415cc00598d6a6fa303/.github/workflows/deploy_production.yml#L6-L22
  # Problem: https://github.community/t/action-does-not-trigger-another-on-push-tag-action/17148
  guard:
    name: Guard
    runs-on: ubuntu-latest
    outputs:
      should_deploy: ${{ steps.changeset-count.outputs.change_count == 0 }}
    steps:
      - uses: actions/checkout@v2

      - id: changeset-count
        run: echo "::set-output name=change_count::$(ls .changeset/*.md | grep -v README | wc -l | xargs)"

      - name: Log changeset count
        run: echo ${{ steps.changeset-count.outputs.change_count }}

  deploy:
    name: Website
    needs: [guard]
    runs-on: ubuntu-latest
    if: ${{ steps.changeset-count.outputs.CHANGE_COUNT == 0 }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Website
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./website/dist
